# Halloy config.
#
# For a complete list of available options,
# please visit https://halloy.chat/configuration/

theme = "Catppuccin Mocha"

[servers.liberachat]
nickname = "tulkdan"
server = "irctoday.com"

[servers.liberachat.sasl.plain]
username = "tulkdan"
password_file = "~/.config/halloy/password"
password_file_first_line_only = true

[font]
family = "Monaspace Krypton"

[platform_specific]
linux.decorations = false
